# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['web_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('web/templates', 'web/templates'),
        ('web/static', 'web/static'),
    ],
    hiddenimports=[
        'flask',
        'jinja2',
        'werkzeug.serving',
        'web.app',
        'web.content_loader',
        'problems.algebra.linear_equations',
        'problems.algebra.inequalities',
        'problems.algebra.quadratics',
        'problems.algebra.exponents_radicals',
        'problems.algebra.word_problems',
        'problems.geometry.angles_lines',
        'problems.geometry.triangles',
        'problems.geometry.polygons',
        'problems.geometry.circles',
        'problems.geometry.coordinate_geometry',
        'problems.advanced.linear_functions',
        'problems.advanced.systems_of_equations',
        'problems.advanced.similar_triangles',
        'problems.advanced.trigonometry',
        'problems.advanced.parabolas_graphs',
        'problems.advanced.circle_equations',
        'problems.advanced.solid_geometry',
        'content.algebra.linear_equations',
        'content.algebra.inequalities',
        'content.algebra.quadratics',
        'content.algebra.exponents_radicals',
        'content.algebra.word_problems',
        'content.geometry.angles_lines',
        'content.geometry.triangles',
        'content.geometry.polygons',
        'content.geometry.circles',
        'content.geometry.coordinate_geometry',
        'content.advanced.linear_functions',
        'content.advanced.systems_of_equations',
        'content.advanced.similar_triangles',
        'content.advanced.trigonometry',
        'content.advanced.parabolas_graphs',
        'content.advanced.circle_equations',
        'content.advanced.solid_geometry',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MathFoundationBuilder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MathFoundationBuilder',
)
app = BUNDLE(
    coll,
    name='MathFoundationBuilder.app',
    icon=None,
    bundle_identifier=None,
)
